# Generated by Django 2.1.7 on 2019-03-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190316_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
